# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pr: none

trigger:
  - master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      git config user.email "kchau@microsoft.com"
      git config user.name "Ken Chau"
      git remote set-url origin https://kenotron:$(git.pat)@github.com/Microsoft/frontend-bootcamp.git
      git checkout master
      git pull
      npm install
      git checkout -b build_$(Build.BuildId)
      npm run build
      git add .
      git commit -m "adding docs"
      git subtree split --prefix docs -b temp_$(Build.BuildId)
      git push origin temp_$(Build.BuildId):refs/heads/gh-pages --force
    displayName: 'npm install, build and push docs to gh-pages'
